name: SammyChien
favicon: null
layout_spectrum: 1
typography_spectrum: 0.01583
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#43625c'
    - '#fe2611'
    - '#000005'
    - '#fefe00'
    - '#ff8f00'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
